---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - clojure
  fixme:
    enabled: true
  kibit:
    enabled: true
ratings:
  paths:
    - "**.clj"
exclude_paths:
  - target/
